---
title: "Bash Tutorial Exercises"
author: "Katherine Wolf"
date: "8/31/2026"
execute:
  echo: true
engine: knitr
---
**1. Make a variable called `mypython` that contains the path to Python on your machine. You shouldn’t need to manually type the path.**

```{bash}
mypython=$(which python)  # create variable with the path
echo $mypython            # print value of variable (i.e., the path)
```

**2. Construct a variable that has the value `<username>@<machinename>` using existing environment variables and the `hostname` utility.**

I wasn't sure if the question intended the value in the variable to include the less-than and greater-than symbols, so I solved the problem both ways. (My laptop's name is "tris" after the character Tris in Divergent. Don't judge me!)

Excluding the less-than and greater-than symbols:

```{bash}
ghost_in_the_machine="$(whoami)@$(hostname)"    # create variable 
echo $ghost_in_the_machine                      # print value of variable
```

Including the less-than and greater-than symbols:
```{bash}
ghost_in_the_machine="<$(whoami)>@<$(hostname)>"    # create variable 
echo $ghost_in_the_machine                          # print value of variable
```

**3. Figure out how to use the `mkdir` command to create the following directory structure in one short command:**

        temp
        
            ├── proj1

                    ├── code

                    └── data

            ├── proj2

                    ├── code

                    └── data

            └── proj3

                    ├── code

                    └── data

```{bash}
mkdir -p temp/proj{1..3}/{code,data}    # create the file structure
ls -R temp    # prove that it worked by printing contents of 'temp' recursively
```

**4. How would you count the number of lines in an input file, say, a data file?**

This code presumes a file exists titled `datafile.txt` in the current working directory. I invented one with the following contents. (The seventh line has commas for later use in problem 9.)

```{bash, echo=FALSE}
cat datafile.txt    # print the data file
```

Code to count the lines:

```{bash}
wc -l datafile.txt    # -l modifier tells the wc function to count the number of new lines
```

**5. Print the first three lines of a file to the screen. Now print just the third line to the screen.**

Using the same file, the first three lines:

```{bash}
head -n 3 datafile.txt
```

Third line only:

```{bash}
sed -n '3p' datafile.txt
```

**6. Put the third line of a file in a new file.**

```{bash}
sed -n '3p' datafile.txt > newfile.txt    # put the third line into a new file
cat newfile.txt                           # print new file to prove that it worked
```

**7. Now add the fifth line of the file to that same file from the previous problem.**

```{bash}
sed -n '5p' datafile.txt >> newfile.txt    # add fifth line to the prior file
cat newfile.txt                            # print new file to prove that it worked
```

**8. Extract the Australia data from the `cpds.csv` dataset and put it in a file called `cpds_australia.csv`. It’s OK if you do this in a straightforward way and it might fail if ‘Australia’ is present in an unexpected column.**

```{bash}
grep Australia cpds.csv > cpds_australia.csv    # extract the Australia data to another file
cat cpds_australia.csv                          # proof that Australia is all that remains
```

**9. Find all the lines in a file that do not contain a comma. (You might use this to look for anomalies in a CSV file.)**

This code uses the same `datafile.txt` file from problems 4–7. The standard output omits the seventh line, the only line with commas in the numbers, as expected.

```{bash}
grep -v "," datafile.txt
```

**10. Write shell code that creates files `file1.txt`, `file2.txt`, `file3.txt`, etc., with the word ‘blah’ as the only line in each file.**

```{bash}
n_of_files=3                    # to change the # of files, change this value
for(( n=1; n<=$n_of_files; n++))          
do
    echo "blah" > file$n.txt    # create each numbered file and its blasé content
    ls -l "file$n.txt"          # print info about each file to prove that each exists
    cat file$n.txt              # print contents of each file to prove its indifference
done
```